FROM node:8.15.1 as build-stage

RUN npm install -g ember-cli@1.13.15
RUN npm install -g bower@1.8.8
RUN npm install -g phantomjs-prebuilt@2.1.16 --unsafe-perm

RUN \
	git clone https://github.com/facebook/watchman.git &&\
	cd watchman &&\
	git checkout v3.5.0 &&\
	./autogen.sh &&\
	./configure &&\
	make &&\
	make install


EXPOSE 4200 35729
WORKDIR /myapp

COPY package*.json ./
COPY bower.json ./

RUN npm install
RUN bower install --allow-root

# this following copies content of host folder to container
COPY ./ /myapp

ARG environment_selector

RUN /usr/local/bin/ember build --environment=$environment_selector
RUN echo "$environment_selector" > /myapp/dist/build_for_environment.txt


# ---------------------

FROM scratch as dist-stage
COPY --from=build-stage /myapp/dist ./


# Run one of the following commands to build and export to dist folder.

# For build usable for test server:
# rm -r dist/ || DOCKER_BUILDKIT=1 docker build -f Dockerfile_build_remote_dev -o dist --build-arg environment_selector=remote_dev .

# For build usable for production server:
# rm -r dist/ || DOCKER_BUILDKIT=1 docker build -f Dockerfile_build_remote_dev -o dist --build-arg environment_selector=production .

