name: Deploy to production server of naskoc.fi

on: 
  workflow_dispatch:
  push:
    branches:
      - prod-naskoc

jobs:
  InvokeBuildAndDeployForProduction:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke KSI dev build and deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy generic
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "host": "ksi", "host_path": "/var/www/naskoc-old-web", "environment_selector": "prod_naskoc" }'
