name: Deploy generic test discord

on: 
  workflow_dispatch:
    inputs:
      host:
        description: 'The host to which the deploy should be made'
        required: true
      host_path:
        description: 'The path to which the deploy should be made'
        required: true
      environment_selector:
        description: 'The build environment selector'
        required: true

jobs:
  BuildAndDeployDiscord:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Get commit hash and branch name
        id: git-vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Send notification to Discord
        uses: joelwmale/webhook-action@2.0.2
        with:
          url: ${{ secrets.DISCORD_DEPLOY_WEBHOOK }}
          headers: '{"Content-Type": "application/json"}'
          body: '{"content": "Deployment finished ${{ github.event.inputs.host }} of ${{ steps.git-vars.outputs.branch }} (commit: ${{ steps.git-vars.outputs.sha_short }} )"}'
