name: Deploy generic

on: 
  workflow_dispatch:
    inputs:
      host:
        description: 'The host to which the deploy should be made'
        required: true
      host_path:
        description: 'The path to which the deploy should be made'
        required: true
      environment_selector:
        description: 'The build environment selector'
        required: true

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # two two currently available plugins for caching don't work - one doesn't work well with buildkit and one has problems accessing the cache 

      -
        name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build --target build_dist_stage -o dist --build-arg environment_selector=${{ github.event.inputs.environment_selector }} .

      - name: Deploy to Aisa
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-avz --delete -r"
            SOURCE: "dist/"
            REMOTE_HOST: aisa.fi.muni.cz
            REMOTE_USER: ${{ secrets.SSH_USER }} # warning: as of 2020-12-05 this was using Ondra B. account
            TARGET: "ksi/github-dist-${{ github.event.inputs.host }}"

      - name: Deploy via SSH from AIsa
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: rsync -avz --delete -r ksi/github-dist-${{ github.event.inputs.host }} ${{ github.event.inputs.host }}:${{ github.event.inputs.host_path }}
          host: aisa.fi.muni.cz
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
