name: Deploy to production server

on: 
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke KSI dev build and deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy generic
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "host": "ksi", "host_path": "/var/www/ksi", "environment_selector": "production" }'
